### ISSUE TITLE
id_token : iat the same as exp

### ISSUE THREAD

**Issue by janul** [SUNET/SATOSA#93]
Hi,
Scenario:  oidc - frontend, saml - backend;
client receives always **id_token** where value of **iat** is the same as **exp**
sample decoded payload:
`
{
  "sub": "e02c372f1a5f8df03265b68f7cdc2e22115eee7f39eb95938480e0c756f14b9f8732ca693f00471d19b80f67a8124b9a1dc587502143ec02daff3b943544a768",
  "iat": 1495527682.2663593,
  "aud": [
    "7FTl3vGXxRpC"
  ],
  "exp": 1495531282.2663598,
  "at_hash": "LgBpOuidp-mVyGMwXTzM6A",
  "iss": "https://op-test.heanet.ie"
}
`
In logs I always get that 'code' has already been used, whis is not true.

Sample exceptions  I get:
`
Traceback (most recent call last):
  File "/opt/satosa/lib/python3.5/site-packages/satosa/frontends/openid_connect.py", line 322, in token_endpoint
    response = self.provider.handle_token_request(urlencode(context.request), headers)
  File "/opt/satosa/lib/python3.5/site-packages/pyop/provider.py", line 313, in handle_token_request
    return self._do_code_exchange(token_request, extra_id_token_claims)
  File "/opt/satosa/lib/python3.5/site-packages/pyop/provider.py", line 353, in _do_code_exchange
    access_token = self.authz_state.exchange_code_for_token(token_request['code'])
  File "/opt/satosa/lib/python3.5/site-packages/pyop/authz_state.py", line 159, in exchange_code_for_token
    raise InvalidAuthorizationCode('{} has already been used'.format(authorization_code))
pyop.exceptions.InvalidAuthorizationCode: a0556ec7d2974e6fbd1879de4000c540 has already been used
[2017-05-23 09:07:26] [DEBUG]: [urn:uuid:70e586d6-05e6-4bb6-a5b9-eb4685ee630f] Saving state as cookie, secure: True, max-age: 1200, path: /
`

**Comment by janul** [comment]
sorry, issue actually is not in satosa code
